In [3]:
dataset1=['python','java','C++']
dataset2=[12,5]
result = zip(dataset1,dataset2)
print(result)

In [2]:
print(list(result))

[('python', 12), ('java', 5), ('C++', 9)]


In [4]:
print(list(result))

[('python', 12), ('java', 5)]


In [6]:
data = {"Name":['Tom','Nick','Crish','Jack'], 'Age':[20,21,19,18]}

In [7]:
import pandas as pd
dfEmpl = pd.DataFrame(data)
print(dfEmpl)


    Name  Age
0    Tom   20
1   Nick   21
2  Crish   19
3   Jack   18


In [8]:
serEmplAge = pd.Series(dfEmpl)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [9]:
serEmplAge = pd.Series(dfEmpl["Age"])
serEmplAge.head(3)

0    20
1    21
2    19
Name: Age, dtype: int64

In [10]:
result serEmplAge.apply(lambda x : 21 if x==19 else x)

SyntaxError: invalid syntax (1395121206.py, line 1)

In [12]:
result = serEmplAge.apply(lambda x : 21 if x==19 else x)
print(result)

0    20
1    21
2    21
3    18
Name: Age, dtype: int64


In [13]:
import numpy as np
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [14]:
array2 = np.zeros((3,3))

In [15]:
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
array3 = np.ones((2,4))
array3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
array4 = np.array((3,4))
array4

array([3, 4])

In [18]:
array5 = np.random.array((3,4))
array5

AttributeError: module 'numpy.random' has no attribute 'array'

In [20]:
array6 = np.random.rand(3,4)
array6

array([[0.19713083, 0.85151076, 0.89186762, 0.98900823],
       [0.56237226, 0.73159295, 0.3182239 , 0.76171767],
       [0.57071621, 0.16180948, 0.01755148, 0.22447403]])

In [21]:
np.save()

TypeError: save() missing 2 required positional arguments: 'file' and 'arr'

In [22]:
array7  = np.reshape(array6,(4,3))
array7

array([[0.19713083, 0.85151076, 0.89186762],
       [0.98900823, 0.56237226, 0.73159295],
       [0.3182239 , 0.76171767, 0.57071621],
       [0.16180948, 0.01755148, 0.22447403]])

In [23]:
array7.shape


(4, 3)

In [24]:
np.transpose(array7)

array([[0.19713083, 0.98900823, 0.3182239 , 0.16180948],
       [0.85151076, 0.56237226, 0.76171767, 0.01755148],
       [0.89186762, 0.73159295, 0.57071621, 0.22447403]])

In [25]:
np.savetxt('data.txt',array7)

In [26]:
new_data = np.loadtxt('data.txt')

In [27]:
new_data

array([[0.19713083, 0.85151076, 0.89186762],
       [0.98900823, 0.56237226, 0.73159295],
       [0.3182239 , 0.76171767, 0.57071621],
       [0.16180948, 0.01755148, 0.22447403]])