In [3]:
dataset1=['python','java','C++']
dataset2=[12,5]
result = zip(dataset1,dataset2)
print(result)

In [2]:
print(list(result))

[('python', 12), ('java', 5), ('C++', 9)]


In [4]:
print(list(result))

[('python', 12), ('java', 5)]


In [6]:
data = {"Name":['Tom','Nick','Crish','Jack'], 'Age':[20,21,19,18]}

In [7]:
import pandas as pd
dfEmpl = pd.DataFrame(data)
print(dfEmpl)


    Name  Age
0    Tom   20
1   Nick   21
2  Crish   19
3   Jack   18


In [8]:
serEmplAge = pd.Series(dfEmpl)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [9]:
serEmplAge = pd.Series(dfEmpl["Age"])
serEmplAge.head(3)

0    20
1    21
2    19
Name: Age, dtype: int64

In [10]:
result serEmplAge.apply(lambda x : 21 if x==19 else x)

SyntaxError: invalid syntax (1395121206.py, line 1)

In [12]:
result = serEmplAge.apply(lambda x : 21 if x==19 else x)
print(result)

0    20
1    21
2    21
3    18
Name: Age, dtype: int64


In [13]:
import numpy as np
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [14]:
array2 = np.zeros((3,3))

In [15]:
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
array3 = np.ones((2,4))
array3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
array4 = np.array((3,4))
array4

array([3, 4])

In [18]:
array5 = np.random.array((3,4))
array5

AttributeError: module 'numpy.random' has no attribute 'array'

In [20]:
array6 = np.random.rand(3,4)
array6

array([[0.19713083, 0.85151076, 0.89186762, 0.98900823],
       [0.56237226, 0.73159295, 0.3182239 , 0.76171767],
       [0.57071621, 0.16180948, 0.01755148, 0.22447403]])

In [21]:
np.save()

TypeError: save() missing 2 required positional arguments: 'file' and 'arr'

In [22]:
array7  = np.reshape(array6,(4,3))
array7

array([[0.19713083, 0.85151076, 0.89186762],
       [0.98900823, 0.56237226, 0.73159295],
       [0.3182239 , 0.76171767, 0.57071621],
       [0.16180948, 0.01755148, 0.22447403]])

In [23]:
array7.shape


(4, 3)

In [24]:
np.transpose(array7)

array([[0.19713083, 0.98900823, 0.3182239 , 0.16180948],
       [0.85151076, 0.56237226, 0.76171767, 0.01755148],
       [0.89186762, 0.73159295, 0.57071621, 0.22447403]])

In [25]:
np.savetxt('data.txt',array7)

In [26]:
new_data = np.loadtxt('data.txt')

In [27]:
new_data

array([[0.19713083, 0.85151076, 0.89186762],
       [0.98900823, 0.56237226, 0.73159295],
       [0.3182239 , 0.76171767, 0.57071621],
       [0.16180948, 0.01755148, 0.22447403]])

In [28]:

a = np.array([[2,1],[4,-5]])
b = np.array([[5],[7]])
from scipy import linalg
x = linalg.solve(a,b)
print(a.dot(x)-b)

[[0.]
 [0.]]


In [29]:
a = np.array([[2,1],[1,-3]])
b = np.array([[5],[-2]])
from scipy import linalg
x = linalg.solve(a,b)
print(a.dot(x)-b)

[[ 0.0000000e+00]
 [-4.4408921e-16]]


In [30]:
print(x)

[[1.85714286]
 [1.28571429]]


In [31]:
print(y)

NameError: name 'y' is not defined

In [32]:

     
class Product:
    def __init__(self, product_id, name, price):
        self.product_id = product_id
        self.name = name
        self.price = price
 
class Customer:
    def __init__(self, customer_id, name, email):
        self.customer_id = customer_id
        self.name = name
        self.email = email
 
class SalesOrder:
    def __init__(self, order_id, customer, products):
        self.order_id = order_id
        self.customer = customer
        self.products = products
 
class SalesManagementSystem:
    def __init__(self):
        self.products = []
        self.customers = []
        self.sales_orders = []
        self.next_product_id = 1
        self.next_customer_id = 1
        self.next_order_id = 1
 
    def add_product(self, name, price):
        product = Product(self.next_product_id, name, price)
        self.products.append(product)
        self.next_product_id += 1
        print(f"Product '{name}' added with ID {product.product_id}")
 
    def list_products(self):
        print("List of Products:")
        for product in self.products:
            print(f"ID: {product.product_id}, Name: {product.name}, Price: {product.price}")
 
    def add_customer(self, name, email):
        customer = Customer(self.next_customer_id, name, email)
        self.customers.append(customer)
        self.next_customer_id += 1
        print(f"Customer '{name}' added with ID {customer.customer_id}")
 
    def list_customers(self):
        print("List of Customers:")
        for customer in self.customers:
            print(f"ID: {customer.customer_id}, Name: {customer.name}, Email: {customer.email}")
 
    def create_sales_order(self, customer_id, product_ids):
        customer = next((c for c in self.customers if c.customer_id == customer_id), None)
        if customer:
            products = [p for p in self.products if p.product_id in product_ids]
            if products:
                order = SalesOrder(self.next_order_id, customer, products)
                self.sales_orders.append(order)
                self.next_order_id += 1
                print(f"Sales order created with ID {order.order_id}")
            else:
                print("Invalid product IDs.")
        else:
            print("Invalid customer ID.")
 
    def list_sales_orders(self):
        print("List of Sales Orders:")
        for order in self.sales_orders:
            print(f"Order ID: {order.order_id}, Customer: {order.customer.name}")
            print("Products:")
            for product in order.products:
                print(f"  - {product.name}: {product.price}")
 
if __name__ == "__main__":
    system = SalesManagementSystem()
    while True:
        print("\nOptions:")
        print("a. Add a new product")
        print("b. List all products")
        print("c. Add a new customer")
        print("d. List all customers")
        print("e. Create a new sales order")
        print("f. List all sales orders")
        print("g. Quit the program")
        choice = input("Enter your choice: ").lower()
 
        if choice == 'a':
            name = input("Enter product name: ")
            price = float(input("Enter product price: "))
            system.add_product(name, price)
        elif choice == 'b':
            system.list_products()
        elif choice == 'c':
            name = input("Enter customer name: ")
            email = input("Enter customer email: ")
            system.add_customer(name, email)
        elif choice == 'd':
            system.list_customers()
        elif choice == 'e':
            customer_id = int(input("Enter customer ID for the sales order: "))
            product_ids = [int(id) for id in input("Enter product IDs separated by spaces: ").split()]
            system.create_sales_order(customer_id, product_ids)
        elif choice == 'f':
            system.list_sales_orders()
        elif choice == 'g':
            print("Exiting the program.")
            break
        else:
            print("Invalid choice. Please select a valid option.")


Options:
a. Add a new product
b. List all products
c. Add a new customer
d. List all customers
e. Create a new sales order
f. List all sales orders
g. Quit the program
Enter your choice: a
Enter product name: Gym
Enter product price: 16000
Product 'Gym' added with ID 1

Options:
a. Add a new product
b. List all products
c. Add a new customer
d. List all customers
e. Create a new sales order
f. List all sales orders
g. Quit the program
Enter your choice: g
Exiting the program.
